const IntegrationData = [
  {
    id: 1,
    to:'/integrations',
    img: "/Images/website-btn.png",
    title: "Whatsapp Website Widget",
    desc: "Drive WhatsApp sales with personalised CTAs",
  },
  {
    id: 2,
    to:'/integrations',
    img: "/Images/whatsapp-link.png",
    title: "Whatsapp Link Generator",
    desc: "Create shareable links & QR for your WA business number",
  },
  {
    id: 3,
    to:'/integrations',
    img: "/Images/dialogflow.png",
    title: "Dialogflow Integration",
    desc: "Involves incorporating Dialogflow, a natural language understanding platform, into your application to enable human-like conversations between users and your application",
  },
  {
    id: 4,
    to:'/integrations',
    img: "/Images/rozarpay.png",
    title: "Rozarpay",
    desc: "Send payment links & subscription updates to drive quick payments",
  },
  {
    id: 5,
    to:'/integrations',
    img: "/Images/earnsight.png",
    title: "Earnsights",
    desc: "Combine all your Marketing and CRM data for full-funnel visibility with a single source of truth with the Marketing data intelligence tool by EasyInsights",
  },
  {
    id: 6,
    to:'/integrations',
    img: "/Images/shopify.png",
    title: "Shopify",
    desc: "Provide live chat support to your customers & boost cart recovery",
  },
  {
    id: 7,
    to:'/integrations',
    img: "/Images/woo.png",
    title: "WooCommerce",
    desc: "Boost your cart recovery & reengage with your customers to upsell",
  },
  {
    id: 8,
    to:'/integrations',
    img: "/Images/pabbly.png",
    title: "Pabbly",
    desc: "Integrate with 800+ apps through direct integration",
  },
  {
    id: 9,
    to:'/integrations',
    img: "/Images/leadsquared.png",
    title: "LeadSquared",
    desc: "Drive WhatsApp communication to your Leads and Customers on Leadsquared CRM seamlessly.",
  },
  {
    id: 10,
    to:'/integrations',
    img: "/Images/webengage.png",
    title: "WebEngage",
    desc: "Drive WhatsApp communication to your Leads and Customers on WebEngage CRM seamlessly.",
  },
  {
    id: 11,
    to:'/integrations',
    img: "/Images/clevertap.png",
    title: "CleverTap",
    desc: "Drive WhatsApp communication to your Leads and Customers on CleverTap CRM seamlessly",
  },
  {
    id: 12,
    to:'/integrations',
    img: "/Images/wherehouse.png",
    title: "Wherehouse",
    desc: "Drive WhatsApp communication to your Leads and Customers on wherehouse CRM seamlessly.",
  },
  {
    id: 13,
    to:'/integrations',
    img: "/Images/moengage.png",
    title: "Moengage",
    desc: "Drive WhatsApp communication to your Leads and Customers on moengage CRM seamlessly.",
  },
  {
    id: 14,
    to:'/integrations',
    img: "/Images/kylas.png",
    title: "Kylas",
    desc: "Drive WhatsApp communication to your Leads and Customers on kylas platform seamlessly.",
  },
  {
    id: 15,
    to:'/integrations',
    img: "/Images/cronberry.png",
    title: "Cronberry",
    desc: "Drive WhatsApp communication to your Leads and Customers on Cronberry platform seamlessly.",
  },
  {
    id: 16,
    to:'/integrations',
    img: "/Images/opencart.png",
    title: "OpenCart",
    desc: "Send updates to users on their WhatsApp & boost cart recovery upto 60%",
  },
  {
    id: 17,
    to:'/integrations',
    img: "/Images/integrately.png",
    title: "Integrately",
    desc: "8M+ ready automation for 800+ Apps with AiSensy direct integration.",
  },
];

export default IntegrationData;
